import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// Layout function must be exported as default export (NEXTJS rule)
export default function RootLayout({children}) {
  // Object descructuing is used to get children property form parameters passed to RootLayout
  // const children = params.children;
  // const {children} = params;

  return (
    // JSX
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className='py-10 px-12 max-w-7xl w-full mx-auto'>
          <ul className='flex gap-10'>
            <li><Link href="/user/orders">Orders</Link></li>
            <li><Link href="/user/settings">Settings</Link></li>
          </ul>
        </nav>
        {children}</body>
    </html>
  );
}
